### ISSUE TITLE
Error - but a block was given

### ISSUE THREAD

**Issue by webmastak** [PixeLInc/rss-feed.cr#1]
Error in src/rssfeed.cr:5: 'RSSFeeder::Feed.new' is not expected to be invoked with a block, but a block was given

RSSFeeder::Feed.new("#{url}", refresh_interval: 5) do |item|

**Comment by PixeLInc** [comment]
Oh right, my apologies.
I forgot to update the README when I changed some things pretty sure.

Give it a try with something like this:
```cr
# alternatively, you can use 5.minutes, 5.hours, etc.
RSSFeeder::Feed.listen("#{url}", refresh_interval: 5.seconds) do |item|
  puts item
end
```

**Comment by webmastak** [comment]
```
require "rss_feed"

url = "https://forum.manjaro.org/c/announcements/stable-updates.rss"

RSSFeeder::Feed.listen("#{url}", refresh_interval: 5.seconds) do |item|
  puts item
end
```
Compiled OK. That's what he gave me:

RSSFeeder::Item(@data={"text" => "\n        ", "title" => "[Stable Update] 2018-09-18 - Kernels, Pamac, LibInput", "creator" => "@philm Philip Müller", "category" => "Stable Updates", "description" => "\n

**Comment by PixeLInc** [comment]
Alright!
Thats good. Now you can do what you want with the data you're given 
IE. `item.title`, `item.creator` `item.text`, etc... and print it out however.

Anyhow - since this issue is resolved, I'll close this. If you have any further issues, feel free to open another one ;p

**Comment by webmastak** [comment]
I will open here another question )

I have code that works with - https://github.com/ruivieira/rss

```
require "rss"
require "file"

refresh_interval = 3600 #seconds 
default_url = "https://forum.manjaro.org/c/announcements/stable-updates.rss"
XDG_CONFIG_HOME = ENV["XDG_CONFIG_HOME"]? || File.expand_path("~/.config")
PATH_URL = File.join(XDG_CONFIG_HOME, "rssfeed_url")
PATH = File.join(XDG_CONFIG_HOME, "rssfeed_history")

unless File.exists? PATH
  File.write PATH, ""
end
unless File.exists? PATH_URL
  File.write PATH_URL, default_url
end

feed = RSS.parse "#{File.read(PATH_URL)}"

loop do #start of the program cycle
  counter = 0
  feed.items.each do |e|
    File.open(PATH, "r+") do |file|
      counter += 1
      if counter == 1
        file << "#{e.title}\n#{e.link}\n#{e.pubDate}\n"
      end
    end
  end

  h = File.read(PATH).split("\n").reverse #read from the history file
  title_f = h.to_a.skip(3).first #get a title feed
  link_f = h.to_a.skip(2).first #get a link feed
  pub_date = h.to_a.skip(1).first.split("#{Time.now.year}").first #date publication
  current_date = Time.now.to_s("%a, %e %b") #current date
  compare_date = "#{pub_date.chomp(" ")}" <=> "#{current_date}" #compare dates

  if compare_date == 0 #if the dates are the same then execute the code....
     #execute code.......
  end

  sleep refresh_interval #sleep and back on the cycle
end #program cycle
```

I did everything I need, namely - condition when you need to perform code:
```
  if compare_date == 0
     #execute code.......
  end
```
I want to make this code work with:
https://github.com/woodruffw/notify.cr or 
https://github.com/splattael/libnotify.cr or
https://github.com/Schlipak/crystal-notify

Can you advise how to do it correctly?
